openapi: "3.0.0"

info:
  title: "SM_iDa_014"
  description: "Here is OPENAPI3 specification yaml format for SM_iDa_014 service with field confines, data masks  and possible length"
  version: "1.3.43"
servers:
  - url: "https://api.vtbbank.ru/statement/"

paths:
  /transactions{accnum}:
    get:
      operationId: accountNumber
      tags:
        - accnum
      description: "acccount number"
      parameters:
        - name: accountNumber
          in: path
          required: true
          schema:
            type: string
            maxLength: 20
        - name: statementDate
          in: query
          description: "statement date"
          schema:
            $ref: "#/components/schemas/date"
          required: true
        - name: curFormat
          in: query
          description: "3 letter currency code as defined by ISO-4217"
          required: false
          schema:
            $ref: "#/components/schemas/curfor"
        - name: accnum mask
          in: query
          required: true
          schema:
            type: string
        
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uuid"


components:
  schemas:
    uuid:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
    date:
      type: string
      pattern: ([0-9]{4})-(?:[0-9]{2})-([0-9]{2})
      example: 2006-06-06
    curfor:
      type: string
      format: iso-4217
      example: EUR