openapi: "3.0.0"
info:
  title: "SM_iDa_014"
  description: "Here is OPENAPI3 specification yaml format for SM_iDa_014 service with field confines, data masks  and possible length"
  version: "1.3.43"
servers:
  - url: "https://api.vtbbank.ru/statement/"
paths:
  /transactions:
    get:
      summary: "list of data as response"
      responses:
        '200':
          description: "correspondingAccount"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/corracc"
                properties:        

components:
  schemas:
    corracc:
      type: string
      maxLength: 20