openapi: "3.0.0"
info:
  title: "SM_iDa_014"
  description: "Here is OPENAPI3 specification yaml format for SM_iDa_014 service with field confines, data masks  and possible length"
  version: "1.3.43"
servers:
  - url: "https://api.vtbbank.ru/statement/"
paths:
  /transactions/{accnum}
    get:
      operationId: accountNumber
      tags:
        - accnum
      description: "acccount number"
      parameters:
        - name: accnum
          in: path
          required: true
          schema:
            type: string
            maxLength: 20
        - name: accnum mask
          in: query
          required: true
          schema:
            type: string
            