openapi: "3.0.0"
info:
  title: "SM_iDa_014"
  description: "Here is OPENAPI3 specification yaml format for SM_iDa_014 service with field confines, data masks  and possible length"
  version: "1.3.43"
servers:
  - url: "https://api.vtbbank.ru/statement/"
paths:
  /transactions:
    get:
      tags:
        - accnum
      summary: "the first necessary field contains account number"
      operationId: "accountNumber"
      parameters:
        - name: limit
          in: query
          description:
      responses: