openapi: "3.0.0"
info:
  title: "SM_iDa_014"
  description: "Here is OPENAPI3 specification yaml format for SM_iDa_014 service with field confines, data masks  and possible length"
  version: "1.3.43"
servers:
  - url: "https://api.vtbbank.ru/statement/"
paths:
  /transactions
    get:
      operationId: transactions
      tags:
      - transactions
      description: "the data of statement operations"
      requestbody:
        description: accountNumber
        required: true
        content:
          application/json:
            schema:
              type: string
              maxLength: 20